title: Default
sections:
  top:
    display: Top
    fields:
      -
        handle: page_heading
        field:
          input_type: text
          type: text
          localizable: true
          listable: hidden
          display: 'Page heading'
      -
        handle: content
        field:
          type: markdown
          display: Content
          localizable: true
      -
        handle: author
        field:
          type: users
          display: Author
          default: current
          localizable: true
          max_items: 1
      -
        handle: template
        field:
          type: template
          display: Template
          localizable: false
